#!/usr/bin/env python3
"""Segunda pasada de poda del .config mikuri: mata familias enteras de módulos."""
import re, sys

CONFIG = sys.argv[1] if len(sys.argv) > 1 else '.config'
lines = open(CONFIG).read().splitlines()

# Patrones de módulos a matar (matchea nombre del símbolo CONFIG_X)
KILL = [
    # Ethernet: todos los vendors excepto INTEL
    r'NET_VENDOR_(?!INTEL)[A-Z0-9_]+$',
    # Drivers ethernet sueltos no-Intel
    r'(E1000|E100$|IGB|IGBVF|IGC|IXGB|IXGBE|I40E|ICE|FM10K|JME|SKGE|SKY2|TIGON3|BNX2X?|CNIC|8139|ATL2?|R8169|VIA_RHINE|VIA_VELOCITY|SIS900|NS83820|DL2K|SUNDANCE|TYPHOON|NETXEN|QLA3XXX|QLCNIC|QLGE|SFC|FEDEX|TEHUTI|B44|CASSINI|NIU|NET_TULIP|DE4X5|WINBOND_840|ULTRA32|TULIP|DM9102|ULI526X|PCNET32|AMD8111|LANCE|ARCNET)',
    # SCSI low-level (sd/sr/sg/ATA_AHCI se quedan)
    r'(AIC7XXX|AIC79XX|AIC94XX|MEGARAID[A-Z0-9_]*|MPT2SAS|MPT3SAS|FUSION|MPTSPI|MPTFC|MPTSCSIH|MPTCTL|QLA2XXX|QLA3XXX|LPFC|BE2NET|CCISS|HPSA|SMARTPQI|PM80XX|PM8001|ARCMSR|ESAS2R|MVSAS|MVUMI|STEX|DC395X|NCR5380|NCR53C8XX|SYMBIOS|53C700|QLOGIC|SCSI_3W|3W_9XXX|3W_SAS|SCSI_ACARD|SCSI_AACRAID|SCSI_AIC94XX|SCSI_AIC79XX|SCSI_AIC7XXX|SCSI_ADVANSYS|SCSI_BFA|SCSI_BNX2|SCSI_BNX2X|SCSI_CHELSIO|SCSI_CXGB3|SCSI_CXGB4|SCSI_DC395X|SCSI_DMX3191D|SCSI_DPT_I2O|SCSI_FDOMAIN|SCSI_GENERIC_NCR|SCSI_HPSA|SCSI_HPTIOP|SCSI_INIA100|SCSI_INITIO|SCSI_IPS|SCSI_MPT2SAS|SCSI_MPT3SAS|SCSI_MVSAS|SCSI_MVUMI|SCSI_PM8001|SCSI_PMCRAID|SCSI_QLA_FC|SCSI_QLA_ISCSI|SCSI_SNI_53C810|SCSI_SNIC|SCSI_STEX|SCSI_SYM53C8XX|SCSI_WD719X|SCSI_AHA1740|SCSI_AIC7XXX|SCSI_GDTH|SCSI_ISCI|SCSI_LASI|SCSI_MESH|SCSI_NSP32|SCSI_QLOGIC_1280)',
    # ISCSI/iSCSI/SRP/FCoE
    r'(SCSI_ISCSI_ATTRS|ISCSI_TCP|ISCSI_BOOT_SYSFS|SCSI_ISNS|SCSI_BNX2_ISCSI|SCSI_CXGB[34]_ISCSI|SCSI_QLA_ISCSI|ISCSI_TARGET|SCSI_SRP|SCSI_FC_ATTRS|FC_TCM|FC_...|LIBFC|FCOE|FCOE_MODULE|LIBFCOE|ZFCP)',
    # Media/DVB: fuera TV digital (no hay sintonizador)
    r'(MEDIA_DIGITAL_TV_SUPPORT|MEDIA_TUNER|DVB_[A-Z0-9_]+|MEDIA_TUNER_[A-Z0-9_]+|DVB_CORE|MEDIA_SDR_SUPPORT|MEDIA_CEC_SUPPORT|CEC_[A-Z])',
    # IIO / industrial
    r'IIO_[A-Z0-9_]+$',
    r'^IIO$',
    # HID: solo GENERIC/LOGITECH
    r'HID_(?!GENERIC|LOGITECH)[A-Z0-9_]+$',
    # Input: touchscreens/tablets/keyboards/joysticks/mouse extras
    r'TOUCHSCREEN_[A-Z0-9_]+',
    r'TABLET_USB_[A-Z0-9_]+',
    r'KEYBOARD_(?!ATKBD)[A-Z0-9_]+',
    r'MOUSE_(?!PS2)[A-Z0-9_]+$',
    r'JOYSTICK_(?!XPAD)[A-Z0-9_]+$',
    r'GAMEPORT',
    r'INPUT_(?!EVDEV|UINPUT)[A-Z0-9_]*$',
    # Sensores hwmon: fuera (coretemp/x86_pkg_temp quedan)
    r'SENSORS_[A-Z0-9_]+',
    r'(LTC|MAX[0-9]|INA[0-9]|ADM[0-9]|ASUS|W8[0-9]|NCT[0-9])[A-Z0-9_]+$',
    # Serial/TTY extras
    r'SERIAL_(?!8250)[A-Z0-9_]+$',
    r'(IPMI|MOXA|ROCKETPORT|CYCLADES|STALLION|IPW|NOZOMI|AUART|MEN_Z188|UARTLITE|SC16IS7XX|MAX310X)',
    # USB: red por USB, storage raro, gadgets
    r'USB_USBNET',
    r'USB_NET_[A-Z0-9_]+',
    r'USB_[A-Z0-9]+_NET',
    r'UMS_[A-Z0-9_]+',
    r'USBIP',
    r'USB_HSO|USB_SIERRA|USB_OPTION|USB_SERIAL[A-Z0-9_]*|USB_WWAN|USB_ACM$|USB_RTL8150|USB_PEGASUS',
    # MTD/UBI/nand
    r'(MTD|UBI|NAND|SPI_NOR|JESD204|COMEDI)[A-Z0-9_]*$',
    # LEDS extras
    r'LEDS_(?!CLASS)[A-Z0-9_]+$',
    # GPIO/pinctrl extra (sunrisepoint/intel quedan)
    r'PINCTRL_(?!SUNRISEPOINT|INTEL|CHERRYVIEW|BROXTON|LEWISBURG|GEMINILAKE|ICELAKE|TIGERLAKE|ALDERLAKE|METEORLAKE)[A-Z0-9_]+$',
    r'GPIO_(?!ICH|INTEL|SYSFS|CDEV)[A-Z0-9_]+$',
    # Extcon/regulator/battery/charger
    r'(EXTCON|REGULATOR|CHARGER|BATTERY)[A-Z0-9_]*$',
    r'POWERCAP',
    # Phononet/decnet/legacy net
    r'(PHONET|DECNET|IPDDP|X25|LAPB|LLC2|ATALK|IPX|NCP)',
    r'NETFILTER_XT_MATCH_(?!CONNTRACK|LIMIT|ADDRTYPE|TCPMSS|MULTICAST|STATISTIC)',
    r'NETFILTER_XT_TARGET_(?!LOG|NFLOG|TCPMSS|MARK|NOTRACK|CONNMARK)',
    r'IP_SET[A-Z0-9_]*$',
    r'IP_VS',
    r'(BRIDGE_NF|EBTABLES|BRIDGE_EBT)[A-Z0-9_]*$',
    # NLS extra (437/850/ISO8859-1/UTF8 quedan)
    r'NLS_(?!CODEPAGE_437|CODEPAGE_850|ISO8859_1|ISO8859_15|UTF8)[A-Z0-9_]+$',
    # V4L: no hay cámara; mantener UVC por si conecta una — matar el resto de tuners/frontends ya cubierto
    r'(VIDEO_(?!DEV|BUF)|SOC_CAMERA|V4L_MEM2MEM|V4L2_[A-Z]|MEDIA_SUPPORT_FILTER|USB_GSPCA|USB_G_WEBCAM)',
    # Android / nvidia-tegra etc
    r'ANDROID[A-Z0-9_]*$',
    r'(GNSS|FPGA_[A-Z]|COUNTER|MUX|PECI|SB105x)',
    # SoundWire (viene con SND_SOC)
    r'(SOUNDWIRE|SLIMBUS)[A-Z0-9_]*$',
    # InfiniBand/RDMA restos
    r'RDMA_[A-Z0-9_]+$',
    r'(I40IW|VMWARE_PVRDMA|MLX[45]|QLNX|S2IO|CSISS)',
    # DRM extra restos
    r'DRM_(?!I915|KMS_HELPER|DISPLAY_HELPER|FBDEV)[A-Z0-9_]+$',
    # Bluetooth ya muerto: hidp/bnep quedados
    r'BT_[A-Z0-9_]+$',
    # md/raid456 extras? keep md. matar raid restos de scsi
    r'(BLK_DEV_3W|BLK_DEV_IDE[A-Z0-9_]*|BLK_DEV_CMD64X|BLK_DEV_SIS5513|BLK_DEV_SLC90E66|BLK_DEV_TRIFLEX|BLK_DEV_CS5520|BLK_DEV_CS5535|BLK_DEV_UMEM|BLK_DEV_UMEM86|BLK_DEV_AEC62XX|BLK_DEV_ALI15X3|BLK_DEV_AMD74XX|BLK_DEV_ATIIXP|BLK_DEV_HPT366|BLK_DEV_JMICRON|BLK_DEV_PIOS... )',
    # Virtio extra no usado
    r'VIRTIO_(?!PCI|BLK|NET|CONSOLE|MMIO|INPUT|MEM|BALLOON|FS|VDPA|VSOCKETS)',
    # netdevices restos
    r'(VXLAN$|BAREUDP|GENEVE|GTP|MACSEC|XFRM_USER|MPLS|TIPC|NCSI|NETCONSOLE|NETPOLL|TUN_TAP$)',
    # IPMI/BMC
    r'(IPMI|ASPEED|KCS|SSIF)[A-Z0-9_]*$',
    # rpmsg/remoteproc (ARM stuff)
    r'(REMOTEPROC|RPMSG|FSL_[A-Z]|IMX[A-Z0-9_]*|QCOM_[A-Z0-9_]+)',
    # fsl/ARM platform
    r'(ARCH_[A-Z0-9_]+|PLAT_[A-Z0-9_]+|SOC_[A-Z0-9_]+)$',
]

KEEP = {
    # Excepciones explícitas aunque coincidan con KILL
    'CONFIG_INPUT_EVDEV', 'CONFIG_INPUT_JOYDEV', 'CONFIG_INPUT_MISC',
    'CONFIG_KEYBOARD_ATKBD', 'CONFIG_MOUSE_PS2', 'CONFIG_JOYSTICK_XPAD',
    'CONFIG_HID_GENERIC', 'CONFIG_HID_LOGITECH', 'CONFIG_HIDRAW', 'CONFIG_UHID',
    'CONFIG_INPUT_UINPUT', 'CONFIG_INPUT_MOUSEDEV_PSAUX',
    'CONFIG_INPUT_KEYSERIAL', 'CONFIG_INPUT_KEYRESET', 'CONFIG_INPUT_KEYCHDEV',
    'CONFIG_INPUT_UKBD', 'CONFIG_INPUT_SOC_BUTTON_ARRAY',
    'CONFIG_MEDIA_SUPPORT', 'CONFIG_VIDEO_DEV', 'CONFIG_USB_VIDEO_CLASS',
    'CONFIG_MEDIA_USB_SUPPORT', 'CONFIG_MEDIA_CAMERA_SUPPORT',
    'CONFIG_V4L2_MEM2MEM', 'CONFIG_VIDEOBUF2_CORE', 'CONFIG_VIDEOBUF2_VMALLOCER',
    'CONFIG_VIDEOBUF2_MEMOPS', 'CONFIG_VIDEOBUF2_DMA_CONTIG',
    'CONFIG_VIDEOBUF2_DVB', 'CONFIG_USB_G_WEBCAM',
    'CONFIG_USB_VIDEO_CLASS', 'CONFIG_MEDIA_USB_SUPPORT',
    'CONFIG_MOUSE_PS2', 'CONFIG_MOUSE_PS2_SYNAPTICS', 'CONFIG_MOUSE_PS2_ALPS',
    'CONFIG_MOUSE_PS2_LOGIPS2PP', 'CONFIG_MOUSE_PS2_TRACKPOINT', 'CONFIG_MOUSE_PS2_CYPRESS',
    'CONFIG_SERIAL_8250', 'CONFIG_SERIAL_8250_CONSOLE', 'CONFIG_SERIAL_8250_DEPRECATED',
    'CONFIG_SERIAL_8250_PNP', 'CONFIG_SERIAL_8250_RSA', 'CONFIG_SERIAL_8250_NR_UARTS',
    'CONFIG_SERIAL_8250_RUNTIME_UARTS', 'CONFIG_SERIAL_8250_DW', 'CONFIG_SERIAL_8250_FINTEK',
    'CONFIG_SERIAL_8250_LPSS', 'CONFIG_SERIAL_CORE', 'CONFIG_SERIAL_CORE_CONSOLE',
    'CONFIG_LEDS_CLASS', 'CONFIG_LEDS_TRIGGERS',
    'CONFIG_GPIO_ICH', 'CONFIG_GPIO_INTEL', 'CONFIG_GPIO_SYSFS', 'CONFIG_GPIO_CDEV',
    'CONFIG_NLS_CODEPAGE_437', 'CONFIG_NLS_CODEPAGE_850', 'CONFIG_NLS_ISO8859_1',
    'CONFIG_NLS_ISO8859_15', 'CONFIG_NLS_UTF8', 'CONFIG_NLS_DEFAULT',
    'CONFIG_IIO', 'CONFIG_EXTCON_USBC', 'CONFIG_SND_USB_AUDIO',
    'CONFIG_VIRTIO_PCI', 'CONFIG_VIRTIO_BLK', 'CONFIG_VIRTIO_NET',
    'CONFIG_VIRTIO_CONSOLE', 'CONFIG_VIRTIO_MMIO', 'CONFIG_VIRTIO_INPUT',
    'CONFIG_VIRTIO_MEM', 'CONFIG_VIRTIO_BALLOON', 'CONFIG_VIRTIO_FS',
    'CONFIG_VIRTIO_VDPA', 'CONFIG_VIRTIO_VSOCKETS', 'CONFIG_VDPA',
    'CONFIG_VIDEO_DEV',
    'CONFIG_THERMAL_WRITABLE_TRIPS', 'CONFIG_DRM_I915',
    'CONFIG_X86_PKG_TEMP_THERMAL', 'CONFIG_INTEL_RAPL',
    'CONFIG_INTEL_POWERCLAMP', 'CONFIG_INTEL_SOC_DTS_THERMAL',
    'CONFIG_DRM_KMS_HELPER', 'CONFIG_DRM_DISPLAY_HELPER', 'CONFIG_DRM_FBDEV_EMULATION',
    'CONFIG_FENCE_TRACE', 'CONFIG_SYNC_FILE',
    'CONFIG_INPUT_KEYBOARD', 'CONFIG_INPUT_MOUSE', 'CONFIG_JOYSTICK',
    'CONFIG_HID_BATTERY_STRENGTH',
    'CONFIG_BT', 'CONFIG_RFKILL', 'CONFIG_CFG80211', 'CONFIG_MAC80211',
    'CONFIG_WATCHDOG', 'CONFIG_WATCHDOG_CORE', 'CONFIG_SOFT_WATCHDOG',
    'CONFIG_USB_HID',
    'CONFIG_SENSORS_CORETEMP', 'CONFIG_SENSORS_PKG_TEMP',
    'CONFIG_MEDIA_ANALOG_TV_SUPPORT',
}

out = []
killed = []
for l in lines:
    m = re.match(r'^CONFIG_([A-Z0-9_]+)=(m|y)$', l)
    if m and m.group(1) not in {k[7:] for k in KEEP}:
        name = m.group(1)
        if any(re.fullmatch(p, name) for p in KILL):
            killed.append(f'CONFIG_{name}={m.group(2)}')
            out.append(f'# CONFIG_{name} is not set')
            continue
    out.append(l)

open(CONFIG, 'w').write('\n'.join(out) + '\n')
print(f'modulos/objs matados: {len(killed)}')
for k in killed[:40]: print(' ', k)
